# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-28 12:22
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='content',
            field=models.CharField(default=datetime.datetime(2016, 6, 28, 12, 22, 7, 457000, tzinfo=utc), max_length=3000),
            preserve_default=False,
        ),
    ]
